//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Web.Api.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Web.Api.Models.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates an database entity chgange.
        /// </summary>
        internal static string ENTITY_CHANGE_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ENTITY_CHANGE_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity change.
        /// </summary>
        internal static string ENTITY_CHANGE_EVENT_NAME {
            get {
                return ResourceManager.GetString("ENTITY_CHANGE_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity related events.
        /// </summary>
        internal static string ENTITY_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ENTITY_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database entity.
        /// </summary>
        internal static string ENTITY_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ENTITY_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host related events.
        /// </summary>
        internal static string HOST_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOST_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string HOST_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("HOST_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License related events.
        /// </summary>
        internal static string LICENSE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("LICENSE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LICENSE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("LICENSE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order related events.
        /// </summary>
        internal static string ORDER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("ORDER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ORDER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("ORDER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates payment intent completion.
        /// </summary>
        internal static string PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_COMPLETED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string PAYMENT_INTENT_COMPLETED_EVENT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_COMPLETED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates payment intent creation.
        /// </summary>
        internal static string PAYMENT_INTENT_CREATED_EVENT_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_CREATED_EVENT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string PAYMENT_INTENT_CREATED_EVENT_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_CREATED_EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment intent related events.
        /// </summary>
        internal static string PAYMENT_INTENT_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment intent.
        /// </summary>
        internal static string PAYMENT_INTENT_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("PAYMENT_INTENT_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation related events.
        /// </summary>
        internal static string RESERVATION_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("RESERVATION_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string RESERVATION_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("RESERVATION_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User related events.
        /// </summary>
        internal static string USER_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("USER_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string USER_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("USER_EVENT_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line.
        /// </summary>
        internal static string WAITING_LINE_EVENT_GROUP_DESCRIPTION {
            get {
                return ResourceManager.GetString("WAITING_LINE_EVENT_GROUP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting line related events.
        /// </summary>
        internal static string WAITING_LINE_EVENT_GROUP_NAME {
            get {
                return ResourceManager.GetString("WAITING_LINE_EVENT_GROUP_NAME", resourceCulture);
            }
        }
    }
}
